version: "3.1"

services:
  typesense:
    image: typesense/typesense:0.21.0
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: typesensekey
    volumes: 
      - ./typesense-data:/data
    ports:
      - 8108:8108
