name: Continuous integration

on:
  push:
    branches:
      - develop
      - main

jobs:
  ci:
    name: continuous integration
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
        php-versions:
          - 8.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, PHP extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@verbose
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl
          coverage: xdebug

      - name: Validate composer.json
        run: composer validate

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: composer install

      # run code quality tools
      - name: analyse code quality
        run: make analyse





